### ISSUE TITLE
一个小错误

### ISSUE THREAD

**Issue by Reyi2323** [CQUT-Programmer/Golang-Doc#11]
在https://golang.halfiisland.com/%E8%AF%AD%E8%A8%80%E5%85%A5%E9%97%A8/%E8%AF%AD%E6%B3%95%E8%BF%9B%E9%98%B6/90.generic.html#%E7%A4%BA%E4%BE%8B这一页中，调用使用了泛型的函数的例子为Sum(3.1415926, 1.114514)>，这个>似乎是多余的
![Screenshot_2023-09-23-23-36-41-687_com microsoft emmx](https://github.com/CQUT-Programmer/Golang-Doc/assets/118646118/cc042d03-96c3-4a73-8ee9-80578e54072d)

**Comment by 246859** [comment]
感谢提醒，如果有能力，可以提交pr

**Comment by 246859** [comment]
已改正
