### ISSUE TITLE
这个网站也是作者维护的吗？

### ISSUE THREAD

**Issue by dividez** [CQUT-Programmer/Golang-Doc#20]
![9aa5c2e1160c921d91519533cd45cdc4](https://github.com/CQUT-Programmer/Golang-Doc/assets/19829513/58c78a50-8f77-41c6-adfd-535c5a3cef59)

https://golang.xiniushu.com/

**Comment by 246859** [comment]
应该是其它人自己搭的，里面的内容还停留在一年前
